# Настройки плагина PlayerNamesHidder
# Права и команды:
# - pnh.show - право на просмотр ников при клике
# - pnh.showall - право на использование /pnh showall

display-type: ACTION_BAR # Варианты: ACTION_BAR, PLAYER_TAG, BOTH
actionbar-format: "Игрок: %player_name%" # Поддерживает плейсхолдеры (включая PlaceholderAPI)
display-time: 2 # Время отображения ника в секундах (для обычного режима)
max-distance: 5.0 # Максимальная дистанция для отображения ника

effects:
  enabled: true
  particle-type: VILLAGER_HAPPY
  particle-amount: 10
  sound-enabled: true
  sound-type: ENTITY_PLAYER_LEVELUP
  sound-volume: 1.0
  sound-pitch: 1.0